
INSERT INTO {table_prefix}layout_module VALUES
(null,"1","so_tools.91","content_top","2"),
(null,"1","so_newletter_custom_popup.74","content_top","1"),
(null,"1","so_quickview.43","content_top","0"),
(null,"1","so_page_builder.33","content_home","1"),
(null,"1","so_searchpro.72","search_block","0"),
(null,"1","so_megamenu.75","content_menu2","0"),
(null,"1","so_megamenu.61","content_menu1","0"),
(null,"1","so_facebook_message.96","content_top","3"),
(null,"1","so_page_builder.35","footer_block1","0");


INSERT INTO {table_prefix}soconfig VALUES
("65503","0","soconfig_general_store","{\"typelayout\":\"1\",\"themecolor\":\"red\",\"toppanel_status\":\"0\",\"toppanel_type\":\"1\",\"phone_status\":\"1\",\"contact_number\":{\"2\":\"&lt;i class=&quot;fa fa-phone-square&quot;&gt;&lt;\\/i&gt; Hotline: (+123)4 567 890\",\"1\":\"&lt;i class=&quot;fa fa-phone-square&quot;&gt;&lt;\\/i&gt; Hotline: (+123)4 567 890\"},\"welcome_message_status\":\"1\",\"welcome_message\":{\"2\":\"&lt;i class=&quot;fa fa-envelope&quot;&gt;&lt;\\/i&gt; Sales@oneshop.com\",\"1\":\"&lt;i class=&quot;fa fa-envelope&quot;&gt;&lt;\\/i&gt; Sales@oneshop.com\"},\"checkout_status\":\"0\",\"lang_status\":\"1\",\"preloader\":\"0\",\"preloader_animation\":\"audio-wave\",\"backtop\":\"1\",\"imgpayment_status\":\"1\",\"imgpayment\":\"catalog\\/demo\\/payment\\/payment.png\",\"copyright\":\"Oneshop \\u00a9 {year} Demo Store. All Rights Reserved. Designed by &lt;a href=&quot;http:\\/\\/www.opencartworks.com\\/&quot; target=&quot;_blank&quot;&gt;OpenCartWorks.Com&lt;\\/a&gt;\",\"typeheader\":\"1\",\"typefooter\":\"1\",\"type_banner\":\"10\"}","1"),
("65508","0","soconfig_social_store","{\"social_fb_status\":\"0\",\"facebook\":\"magentech\",\"social_twitter_status\":\"0\",\"twitter\":\"smartaddons\",\"social_custom_status\":\"0\",\"video_code\":{\"2\":\"Custom block Html\",\"1\":\"Custom block Html\"}}","1"),
("65507","0","soconfig_fonts_store","{\"body_status\":\"google\",\"normal_body\":\"Arial, Helvetica, sans-serif\",\"url_body\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Roboto:300,400,500,700\",\"family_body\":\"\'Roboto\', sans-serif\",\"selector_body\":\"body, #wrapper\",\"menu_status\":\"standard\",\"normal_menu\":\"inherit\",\"url_menu\":\"\",\"family_menu\":\"\",\"selector_menu\":\"\",\"heading_status\":\"standard\",\"normal_heading\":\"inherit\",\"url_heading\":\"\",\"family_heading\":\"\",\"selector_heading\":\"\"}","1"),
("65505","0","soconfig_layout_store","{\"layoutstyle\":\"full\",\"theme_bgcolor\":\"#7a167a\",\"pattern\":\"6\",\"contentbg\":\"\",\"content_bg_mode\":\"repeat\",\"content_attachment\":\"scroll\"}","1"),
("65506","0","soconfig_pages_store","{\"product_catalog_refine\":\"2\",\"catalog_refine_devices_lg\":\"6\",\"catalog_refine_devices_md\":\"6\",\"catalog_refine_devices_sm\":\"4\",\"catalog_refine_devices_xs\":\"1\",\"lstimg_cate_status\":\"0\",\"product_catalog_mode\":\"0\",\"product_catalog_column_lg\":\"3\",\"product_catalog_column_md\":\"3\",\"product_catalog_column_sm\":\"2\",\"product_catalog_column_xs\":\"1\",\"other_catalog_column_lg\":\"4\",\"other_catalog_column_md\":\"3\",\"other_catalog_column_sm\":\"2\",\"other_catalog_column_xs\":\"1\",\"new_status\":\"1\",\"days\":\"30\",\"quick_status\":\"1\",\"discount_status\":\"1\",\"countdown_status\":\"1\",\"secondimg\":\"2\",\"rating_status\":\"1\",\"radio_style\":\"0\",\"product_gallerysize\":\"medium\",\"thumbnails_position\":\"bottom\",\"product_enablezoom\":\"1\",\"product_zoommode\":\"inner\",\"product_zoomlenssize\":\"250\",\"tabs_position\":\"2\",\"product_page_button\":\"1\",\"product_socialshare\":{\"2\":\"&lt;div class=&quot;title-share&quot;&gt;Share This&lt;\\/div&gt;\\r\\n&lt;div class=&quot;wrap-content&quot;&gt;&lt;div class=&quot;addthis_inline_share_toolbox&quot;&gt;&lt;\\/div&gt;&lt;\\/div&gt;\",\"1\":\"&lt;div class=&quot;title-share&quot;&gt;Share This&lt;\\/div&gt;\\r\\n&lt;div class=&quot;wrap-content&quot;&gt;&lt;div class=&quot;addthis_inline_share_toolbox&quot;&gt;&lt;\\/div&gt;&lt;\\/div&gt;\"},\"related_status\":\"1\",\"related_position\":\"horizontal\",\"product_related_column_lg\":\"3\",\"product_related_column_md\":\"3\",\"product_related_column_sm\":\"2\",\"product_related_column_xs\":\"1\"}","1"),
("65504","0","soconfig_advanced_store","{\"name_color\":\"red\",\"theme_color\":\"#f44236\",\"scsscompile\":\"0\",\"scssformat\":\"Expanded\",\"compileMutiColor\":\"0\"}","1"),
("64017","1","soconfig_layout_store","{\"layoutstyle\":\"full\",\"theme_bgcolor\":\"#7a167a\",\"pattern\":\"6\",\"contentbg\":\"\",\"content_bg_mode\":\"repeat\",\"content_attachment\":\"scroll\"}","1"),
("64018","1","soconfig_pages_store","{\"product_catalog_refine\":\"0\",\"catalog_refine_devices_lg\":\"4\",\"catalog_refine_devices_md\":\"3\",\"catalog_refine_devices_sm\":\"2\",\"catalog_refine_devices_xs\":\"1\",\"lstimg_cate_status\":\"1\",\"product_catalog_mode\":\"0\",\"product_catalog_column_lg\":\"3\",\"product_catalog_column_md\":\"2\",\"product_catalog_column_sm\":\"2\",\"product_catalog_column_xs\":\"1\",\"other_catalog_column_lg\":\"4\",\"other_catalog_column_md\":\"3\",\"other_catalog_column_sm\":\"2\",\"other_catalog_column_xs\":\"1\",\"new_status\":\"1\",\"days\":\"30\",\"quick_status\":\"1\",\"discount_status\":\"1\",\"countdown_status\":\"1\",\"secondimg\":\"2\",\"rating_status\":\"1\",\"radio_style\":\"1\",\"check_style\":\"1\",\"product_gallerysize\":\"small\",\"thumbnails_position\":\"bottom\",\"product_enablezoom\":\"1\",\"product_zoommode\":\"inner\",\"product_zoomlenssize\":\"250\",\"tabs_position\":\"2\",\"product_page_button\":\"1\",\"product_socialshare\":{\"2\":\"Custom block Html\",\"1\":\"Custom block Html\"},\"related_status\":\"1\",\"related_position\":\"horizontal\",\"product_related_column_lg\":\"4\",\"product_related_column_md\":\"3\",\"product_related_column_sm\":\"2\",\"product_related_column_xs\":\"1\"}","1"),
("64019","1","soconfig_fonts_store","{\"body_status\":\"standard\",\"normal_body\":\"Arial, Helvetica, sans-serif\",\"url_body\":\"\",\"family_body\":\"\",\"selector_body\":\"body\",\"menu_status\":\"standard\",\"normal_menu\":\"inherit\",\"url_menu\":\"\",\"family_menu\":\"\",\"selector_menu\":\"\",\"heading_status\":\"standard\",\"normal_heading\":\"inherit\",\"url_heading\":\"\",\"family_heading\":\"\",\"selector_heading\":\"\"}","1"),
("64020","1","soconfig_social_store","{\"social_fb_status\":\"1\",\"facebook\":\"magentech\",\"social_twitter_status\":\"1\",\"twitter\":\"smartaddons\",\"social_custom_status\":\"1\",\"video_code\":{\"2\":\"Custom block Html\",\"1\":\"Custom block Html\"}}","1"),
("64015","1","soconfig_general_store","{\"typelayout\":\"1\",\"themecolor\":\"blue\",\"toppanel_status\":\"0\",\"toppanel_type\":\"1\",\"phone_status\":\"0\",\"contact_number\":{\"2\":\"(84+) 1234455667\",\"1\":\"(84+) 1234455669\"},\"welcome_message_status\":\"0\",\"welcome_message\":{\"2\":\"Welcome Message Arabic\",\"1\":\"Welcome Message Layout2\"},\"wishlist_status\":\"0\",\"checkout_status\":\"0\",\"lang_status\":\"0\",\"preloader\":\"1\",\"preloader_animation\":\"double-loop\",\"backtop\":\"1\",\"imgpayment_status\":\"1\",\"imgpayment\":\"catalog\\/demo\\/payment\\/payment.png\",\"copyright\":\"SO Revo \\u00c2\\u00a9 2015 - {year}. All Rights Reserved. Designed by &lt;a href=\",\"typeheader\":\"1\",\"typefooter\":\"1\",\"type_banner\":\"4\"}","1"),
("64016","1","soconfig_advanced_store","{\"name_color\":\"blue\",\"theme_color\":\"#1fcf9d\",\"scsscompile\":\"1\",\"scssformat\":\"Nested\",\"compileMutiColor\":\"0\",\"minify_css\":\"0\",\"minify_js\":\"0\"}","1"),
("65214","2","soconfig_social_store","{\"social_fb_status\":\"0\",\"facebook\":\"magentech\",\"social_twitter_status\":\"0\",\"twitter\":\"smartaddons\",\"social_custom_status\":\"0\",\"video_code\":{\"2\":\"Custom block Html\",\"1\":\"Custom block Html\"}}","1"),
("65213","2","soconfig_fonts_store","{\"body_status\":\"google\",\"normal_body\":\"Arial, Helvetica, sans-serif\",\"url_body\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Poppins:300,400,500,600,700\",\"family_body\":\"\'Poppins\', sans-serif\",\"selector_body\":\"body, #wrapper\",\"menu_status\":\"google\",\"normal_menu\":\"inherit\",\"url_menu\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Roboto:300,400,500,700\",\"family_menu\":\"\'Roboto\', sans-serif\",\"selector_menu\":\".font-title,.container-megamenu.horizontal ul.megamenu &gt; li &gt; a,ul.megamenu li .sub-menu .content ul li a, .breadcrumbs .current-name, ul.breadcrumb li a, .so-deal .item-time-w, .modtitle, .so_filter_wrap, .module h2,.container-megamenu.vertical \",\"heading_status\":\"standard\",\"normal_heading\":\"inherit\",\"url_heading\":\"\",\"family_heading\":\"\",\"selector_heading\":\"\"}","1"),
("65210","2","soconfig_advanced_store","{\"name_color\":\"blue\",\"theme_color\":\"#cf1f42\",\"scsscompile\":\"1\",\"scssformat\":\"Nested\",\"compileMutiColor\":\"0\"}","1"),
("65211","2","soconfig_layout_store","{\"layoutstyle\":\"full\",\"theme_bgcolor\":\"#7a167a\",\"pattern\":\"6\",\"contentbg\":\"\",\"content_bg_mode\":\"repeat\",\"content_attachment\":\"scroll\"}","1"),
("65212","2","soconfig_pages_store","{\"product_catalog_refine\":\"2\",\"catalog_refine_devices_lg\":\"4\",\"catalog_refine_devices_md\":\"3\",\"catalog_refine_devices_sm\":\"2\",\"catalog_refine_devices_xs\":\"1\",\"lstimg_cate_status\":\"0\",\"product_catalog_mode\":\"0\",\"product_catalog_column_lg\":\"3\",\"product_catalog_column_md\":\"2\",\"product_catalog_column_sm\":\"2\",\"product_catalog_column_xs\":\"1\",\"other_catalog_column_lg\":\"4\",\"other_catalog_column_md\":\"3\",\"other_catalog_column_sm\":\"2\",\"other_catalog_column_xs\":\"1\",\"new_status\":\"1\",\"days\":\"30\",\"quick_status\":\"1\",\"discount_status\":\"1\",\"countdown_status\":\"1\",\"secondimg\":\"2\",\"rating_status\":\"1\",\"radio_style\":\"1\",\"product_gallerysize\":\"medium\",\"thumbnails_position\":\"bottom\",\"product_enablezoom\":\"1\",\"product_zoommode\":\"inner\",\"product_zoomlenssize\":\"250\",\"tabs_position\":\"1\",\"product_page_button\":\"1\",\"product_socialshare\":{\"2\":\"&lt;div class=&quot;title-share&quot;&gt;Share This&lt;\\/div&gt;\\r\\n&lt;div class=&quot;wrap-content&quot;&gt;&lt;div class=&quot;addthis_inline_share_toolbox&quot;&gt;&lt;\\/div&gt;&lt;\\/div&gt;\",\"1\":\"&lt;div class=&quot;title-share&quot;&gt;Share This&lt;\\/div&gt;\\r\\n&lt;div class=&quot;wrap-content&quot;&gt;&lt;div class=&quot;addthis_inline_share_toolbox&quot;&gt;&lt;\\/div&gt;&lt;\\/div&gt;\"},\"related_status\":\"1\",\"related_position\":\"horizontal\",\"product_related_column_lg\":\"3\",\"product_related_column_md\":\"3\",\"product_related_column_sm\":\"2\",\"product_related_column_xs\":\"1\"}","1"),
("65209","2","soconfig_general_store","{\"typelayout\":\"2\",\"themecolor\":\"yellow\",\"toppanel_status\":\"0\",\"toppanel_type\":\"1\",\"phone_status\":\"1\",\"contact_number\":{\"2\":\"Call Us Now: 0123-444-666\",\"1\":\"Call Us Now: 0123-444-666\"},\"welcome_message_status\":\"1\",\"welcome_message\":{\"2\":\"Welcome Guest\",\"1\":\"Welcome Guest\"},\"checkout_status\":\"1\",\"lang_status\":\"1\",\"preloader\":\"1\",\"preloader_animation\":\"double-loop\",\"backtop\":\"1\",\"imgpayment_status\":\"1\",\"imgpayment\":\"catalog\\/demo\\/payment\\/payment.png\",\"copyright\":\"Etrostores \\u00a9 {year} Demo Store. All Rights Reserved. Designed by &lt;a href=&quot;http:\\/\\/www.opencartworks.com\\/&quot; target=&quot;_blank&quot;&gt;OpenCartWorks.Com&lt;\\/a&gt;\",\"typeheader\":\"2\",\"typefooter\":\"2\",\"type_banner\":\"7\"}","1"),
("65260","3","soconfig_pages_store","{\"product_catalog_refine\":\"2\",\"catalog_refine_devices_lg\":\"4\",\"catalog_refine_devices_md\":\"3\",\"catalog_refine_devices_sm\":\"2\",\"catalog_refine_devices_xs\":\"1\",\"lstimg_cate_status\":\"0\",\"product_catalog_mode\":\"0\",\"product_catalog_column_lg\":\"4\",\"product_catalog_column_md\":\"2\",\"product_catalog_column_sm\":\"2\",\"product_catalog_column_xs\":\"1\",\"other_catalog_column_lg\":\"4\",\"other_catalog_column_md\":\"3\",\"other_catalog_column_sm\":\"2\",\"other_catalog_column_xs\":\"1\",\"new_status\":\"1\",\"days\":\"30\",\"quick_status\":\"1\",\"discount_status\":\"1\",\"countdown_status\":\"1\",\"secondimg\":\"2\",\"rating_status\":\"1\",\"radio_style\":\"1\",\"product_gallerysize\":\"medium\",\"thumbnails_position\":\"left\",\"product_enablezoom\":\"1\",\"product_zoommode\":\"inner\",\"product_zoomlenssize\":\"250\",\"tabs_position\":\"2\",\"product_page_button\":\"1\",\"product_socialshare\":{\"2\":\"&lt;div class=&quot;title-share&quot;&gt;Share This&lt;\\/div&gt;\\r\\n&lt;div class=&quot;wrap-content&quot;&gt;&lt;div class=&quot;addthis_inline_share_toolbox&quot;&gt;&lt;\\/div&gt;&lt;\\/div&gt;\",\"1\":\"&lt;div class=&quot;title-share&quot;&gt;Share This&lt;\\/div&gt;\\r\\n&lt;div class=&quot;wrap-content&quot;&gt;&lt;div class=&quot;addthis_inline_share_toolbox&quot;&gt;&lt;\\/div&gt;&lt;\\/div&gt;\"},\"related_status\":\"1\",\"related_position\":\"vertical\",\"product_related_column_lg\":\"4\",\"product_related_column_md\":\"3\",\"product_related_column_sm\":\"2\",\"product_related_column_xs\":\"1\"}","1"),
("65262","3","soconfig_social_store","{\"social_fb_status\":\"0\",\"facebook\":\"magentech\",\"social_twitter_status\":\"0\",\"twitter\":\"smartaddons\",\"social_custom_status\":\"0\",\"video_code\":{\"2\":\"Custom block Html\",\"1\":\"Custom block Html\"}}","1"),
("65257","3","soconfig_general_store","{\"typelayout\":\"3\",\"themecolor\":\"yellow\",\"toppanel_status\":\"0\",\"toppanel_type\":\"1\",\"phone_status\":\"1\",\"contact_number\":{\"2\":\"Call Us Now: 0123-444-666\",\"1\":\"Call Us Now: 0123-444-666\"},\"welcome_message_status\":\"1\",\"welcome_message\":{\"2\":\"Welcome Guest\",\"1\":\"Welcome Guest\"},\"checkout_status\":\"1\",\"lang_status\":\"1\",\"preloader\":\"1\",\"preloader_animation\":\"double-loop\",\"backtop\":\"1\",\"imgpayment_status\":\"1\",\"imgpayment\":\"catalog\\/demo\\/payment\\/payment.png\",\"copyright\":\"Etrostores \\u00a9 {year} Demo Store. All Rights Reserved. Designed by &lt;a href=&quot;http:\\/\\/www.opencartworks.com\\/&quot; target=&quot;_blank&quot;&gt;OpenCartWorks.Com&lt;\\/a&gt;\",\"typeheader\":\"3\",\"typefooter\":\"3\",\"type_banner\":\"10\"}","1"),
("65261","3","soconfig_fonts_store","{\"body_status\":\"google\",\"normal_body\":\"Arial, Helvetica, sans-serif\",\"url_body\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Poppins:300,400,500,600,700\",\"family_body\":\"\'Poppins\', sans-serif\",\"selector_body\":\"body, #wrapper\",\"menu_status\":\"google\",\"normal_menu\":\"inherit\",\"url_menu\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Roboto:300,400,500,700\",\"family_menu\":\"\'Roboto\', sans-serif\",\"selector_menu\":\".font-title,.container-megamenu.horizontal ul.megamenu &gt; li &gt; a,ul.megamenu li .sub-menu .content ul li a, .breadcrumbs .current-name, ul.breadcrumb li a, .so-deal .item-time-w, .modtitle, .so_filter_wrap, .module h2,.container-megamenu.vertical\",\"heading_status\":\"standard\",\"normal_heading\":\"inherit\",\"url_heading\":\"\",\"family_heading\":\"\",\"selector_heading\":\"\"}","1"),
("65258","3","soconfig_advanced_store","{\"name_color\":\"blue\",\"theme_color\":\"#1f83cf\",\"scsscompile\":\"0\",\"scssformat\":\"Nested\",\"compileMutiColor\":\"0\"}","1"),
("65259","3","soconfig_layout_store","{\"layoutstyle\":\"full\",\"theme_bgcolor\":\"#7a167a\",\"pattern\":\"6\",\"contentbg\":\"\",\"content_bg_mode\":\"repeat\",\"content_attachment\":\"scroll\"}","1");


